//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btlAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBiYTe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThietBiYTe()
        {
            this.ChiTietHDBs = new HashSet<ChiTietHDB>();
        }
    
        public string MaThietBi { get; set; }
        public string MaLoai { get; set; }
        public string MaHang { get; set; }
        public string TenThietBi { get; set; }
        public string GioiThieu { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string Anh { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<bool> An { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> TongSoSao { get; set; }
        public Nullable<int> TongSoDanhGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHDB> ChiTietHDBs { get; set; }
        public virtual HangThietBi HangThietBi { get; set; }
        public virtual LoaiThietBi LoaiThietBi { get; set; }
    }
}
